FROM node:24-slim
WORKDIR /app

# Copy package files and install all dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the code and build the React app
COPY . .
RUN npm run build

# Install 'serve', a robust static file web server
RUN npm install -g serve

# Cloud Run defaults to 8080
ENV PORT=8080
EXPOSE 8080

# Serve the 'dist' folder generated by Vite exactly on 0.0.0.0:8080
CMD ["serve", "-s", "dist", "-l", "tcp://0.0.0.0:8080"]